### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by Alexr03** [recoord/api-shared#25]
Hey! 
First of all, not sure if this repo is meant to be public 😅

Regardless -- 
I'm interested in communicating with VEO programmatically with an API. To get recordings, analytics etc, Support told me its not possible... :( but then I found this repo.

I see that this repo communicates with an API with a user/pass to get a recording data. This available to be used to the public? If so how does one get this information?

Thanks!

**Comment by sazo** [comment]
Hallo Alex,

First of all thanks for showing interest in VEO. 

At the moment VEO sadly does not expose any official API for consumers to use. :) We have talked about it internally, but nothing on the roadmap yet. 

PS: And yes its meant to be public :)
